part of 'url_filter.dart';

//=================================================//

/// Contains the log likelihoods used to make a multinomial naive bayes prediction.
///
/// (Code generated by python script `model/url.ipynb`)
const vocabulary = Dictionary(
{'%': Region(0, 0),
'.': Region(1, 1),
'/': Region(2, 2),
':': Region(3, 3),
'?': Region(4, 4),
'@': Region(5, 5),
'i': Region(6, 6),
'l': Region(7, 7),
's': Region(8, 8),
'{': Region(9, 14),
},
[DictEntry('%', -6.723405943015436, -5.909200193249978),
DictEntry('.', -3.4181559399531825, -3.2995254398999876),
DictEntry('//', -13.812092924502473, -8.613133873258747),
DictEntry(':', -8.768667807583228, -7.680764129109036),
DictEntry('?', -6.060760985934987, -5.711256041217915),
DictEntry('@', -11.396179146201424, -8.73100063646573),
DictEntry('ip', -14.728383656376629, -8.846713472831892),
DictEntry('len', -0.19469108740248586, -0.18587652821145717),
DictEntry('sub', -2.3509226149471463, -2.4686119621756806),
DictEntry('{{id}}', -11.489705204212248, -7.517876166736789),
DictEntry('{{jnk}}', -5.577527931235338, -5.798652062541709),
DictEntry('{{lword}}', -6.453814195562726, -6.532437258829129),
DictEntry('{{num}}', -9.682810310919091, -5.6882021513296),
DictEntry('{{other}}', -7.286086227011184, -6.065437970862419),
DictEntry('{{word}}', -3.243172029973916, -3.4962275605227973),
],
);